language: php
php:
  - "7.4"
branches:
  only:
  - main
  - develop
before_script:
  - composer install
script:
  - composer run demo
  - composer run readme
  - composer run coverage
after_success:
  - git reset -hard
